/*
 * Coex Task Runtime - Thread management for structured concurrency
 *
 * This runtime provides pthread wrappers for task spawning, joining,
 * and cancellation. It is linked into compiled Coex programs.
 */

#ifndef COEX_TASK_H
#define COEX_TASK_H

#include <pthread.h>
#include <stdatomic.h>
#include <stdbool.h>
#include <stdint.h>
#include <stddef.h>

/*
 * Forward declaration for shared waiter (used by wait_any)
 */
struct SharedWaiter;

/*
 * TaskClosure - Per-task execution context
 *
 * Allocated by parent before spawn, passed to child thread.
 * Parent reads result/exception after join.
 *
 * Memory layout: First 5 fields must match LLVM struct in codegen/task.py.
 * Fields after 'completed' are only accessed by C runtime.
 */
typedef struct TaskClosure {
    void* params;               // Pointer to parameter struct (task-specific)
    void* result;               // Return value (i64 handle or pointer)
    void* exception;            // Exception if failed (i64 handle or pointer)
    atomic_bool cancelled;      // Cancellation requested flag
    atomic_bool completed;      // Task finished flag
    pthread_mutex_t mutex;      // For completion signaling
    pthread_cond_t cond;        // For completion signaling
    struct SharedWaiter* shared_waiter;  // Optional shared waiter for wait_any
} TaskClosure;

/*
 * Task entry function type
 * Trampoline generated by compiler calls this signature
 */
typedef void (*TaskEntryFn)(TaskClosure*);

/*
 * Thread handle wrapper for cross-platform compatibility
 */
typedef pthread_t CoexThreadHandle;

/* ============================================================
 * Core Task Functions
 * ============================================================ */

/*
 * Allocate a TaskClosure with space for parameters.
 * Uses malloc; caller responsible for freeing after join.
 *
 * @param params_size  Size of parameter struct in bytes (can be 0)
 * @return             Pointer to initialized TaskClosure
 */
TaskClosure* coex_task_closure_alloc(size_t params_size);

/*
 * Free a TaskClosure and its synchronization primitives.
 * Call after extracting result from joined task.
 *
 * @param closure  Pointer to TaskClosure to free
 */
void coex_task_closure_free(TaskClosure* closure);

/*
 * Spawn a new thread to execute a task.
 *
 * @param entry    Entry function (compiler-generated trampoline)
 * @param closure  TaskClosure with parameters set
 * @return         Thread handle for later joining
 */
CoexThreadHandle coex_task_spawn(TaskEntryFn entry, TaskClosure* closure);

/*
 * Join a thread, blocking until completion.
 *
 * @param thread  Handle from coex_task_spawn
 */
void coex_task_join(CoexThreadHandle thread);

/* ============================================================
 * Cancellation
 * ============================================================ */

/*
 * Request cancellation of a task.
 * Sets atomic flag; task must check at safepoints.
 *
 * @param closure  TaskClosure of task to cancel
 */
void coex_task_cancel(TaskClosure* closure);

/*
 * Check if cancellation has been requested.
 * Called at compiler-generated safepoints.
 *
 * @param closure  TaskClosure of current task
 * @return         true if cancellation requested
 */
bool coex_task_is_cancelled(TaskClosure* closure);

/* ============================================================
 * Completion Signaling
 * ============================================================ */

/*
 * Signal that task has completed.
 * Called by trampoline after storing result/exception.
 *
 * @param closure  TaskClosure of completed task
 */
void coex_task_signal_complete(TaskClosure* closure);

/*
 * Wait for a task to complete.
 * Blocks until completion flag is set.
 *
 * @param closure  TaskClosure to wait on
 */
void coex_task_wait_complete(TaskClosure* closure);

/* ============================================================
 * Collection Operations (for first/most blocks)
 * ============================================================ */

/*
 * Wait for any one of multiple tasks to complete.
 * Used by 'first' collection blocks.
 *
 * @param closures  Array of TaskClosure pointers
 * @param count     Number of closures
 * @return          Index of first completed task
 */
int coex_task_wait_any(TaskClosure** closures, int count);

/*
 * Wait for all tasks to complete.
 * Used by 'for' and 'most' collection blocks.
 *
 * @param closures  Array of TaskClosure pointers
 * @param count     Number of closures
 */
void coex_task_wait_all(TaskClosure** closures, int count);

/* ============================================================
 * Safepoint Support (TLS-based)
 * ============================================================ */

/*
 * Set the current task's closure for this thread.
 * Called by trampoline at task entry.
 * Pass NULL at task exit to clear.
 *
 * @param closure  TaskClosure for current task, or NULL
 */
void coex_task_set_current(TaskClosure* closure);

/*
 * Get the current task's closure for this thread.
 * Returns NULL if not in a task context.
 *
 * @return  Current TaskClosure or NULL
 */
TaskClosure* coex_task_get_current(void);

/*
 * Check if current task should exit due to cancellation.
 * Called at compiler-generated safepoints (loop back-edges).
 * Returns immediately if not in a task context.
 *
 * @return  1 if task is cancelled and should exit, 0 otherwise
 */
int coex_task_check_safepoint(void);

#endif /* COEX_TASK_H */
